# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_plain:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbboxOo0jyL3DNxqZ6UTEnZPEzPDPnujEYaClqNWSLWkphczHKAnJPkrwbAWB4JbJKjsAJ5kn53f10KPnUyZvJ5Jn8Rpf7RM7+56MYaBg84gVoA2KeIYxUa7h8neY7J61Galp0c6cOK+hp1lPsoiBSdCW/Rtbv6ALCcVe+4+uCW5FRoJcNRJfGRLRnjh1pw57HQw9O55mf319s4rVUq4umznQ0CciEx3rVMtXf4xjIZDZAhNpGaBh8AtHauaMZCOGociAIquYYqoSQnnmnOBiduRa5OkvGZomgybNQivlYboDeF6sQ71KVzRXSI+mxCYbSp246lqSdQtQsjFA54NYl/qWgAql0uqCqsZidW+XBjquyItRl2Rfzzy5Fk/gMOAJXHQYp4POfgFbqtxjWpfnuOKqW/1IGWcIt2g016effUqGgj/oePX0g+duFdszSKK773rJBySgafFF6XWNqagrLmE4LUGC+6P3oxzYTSFGeUVA21OayL+K40XPpJti5zns= # devops-eth2-shared"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDH6k3/3zfV2LiFoT1xXE888iKHlOhJTLukH8QXn8aPp0zEiDBDknoyCPTt/Cr/q2Z0qMbIz7M3AlOvC9Dr1sJ0TTSdViJSBgZqNQ+SFUdUj/dlDRf7AuQ0Pe0QzK6bODmEpjR9SIc/l1lhjmFDZokESJhwgtg6aV5z4il98ysyKYlJ0QATYoHAFoeVqIyjDQtErn2qFuvu3LrY5B2rjVirUjNkz4RpBOWM9GTfAMDdyMy4c+xWixq6nWiEEOprasPyik+BvqWpj+UokvqQMNp8c1lhtUC6+RB5zOjg/5Z2vkUI3GFL5dNdPhRAGzcnnxSXYRJ9CFAa+ASmV8mzTyvQSFV1Xs3vzotFR6wCjDzy1XZbou4+HLmCjZ7Cb4P6rG1fAho5lyA83b7Eyf1ZUAMfcVbAB4x6IWyQNu9kdNkFFG+cb1y+qDvRcsmNJ84tb12vRpWebPmnTOPXiyvBUzzVn6wyGei1aZKpYm5GMjB2tGIUJML6Z9WsSnpcgyWSocM= # snapshotter"
bootstrap_default_user_authorized_keys_github_all:
  - barnabasbusa
  - parithosh
  - samcm
  - savid
  - skylenet
  - pk910
bootstrap_default_user_authorized_keys_github: >
  {{
    (bootstrap_default_user_authorized_keys_github_all | default([]))
  }}
prometheus_remote_push_url: https://victoriametrics-public.analytics.production.platform.ethpandaops.io/insert/1/prometheus/api/v1/write
prometheus_remote_write_username: "{{ secret_prometheus_remote_write.username }}"
prometheus_remote_write_password: "{{ secret_prometheus_remote_write.password }}"
prometheus_container_name: "prometheus_exporter"
prometheus_container_image: "prom/prometheus:latest"
prometheus_config: |
  global:
    scrape_interval: 12s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
      instance: "kurtosis-sync-test"
      ip_address: "{{ ansible_host }}"
  remote_write:
    - queue_config:
        batch_send_deadline: 5s
        max_backoff: 500ms
        max_samples_per_send: 500
        min_backoff: 50ms
        max_shards: 100
      url: {{ prometheus_remote_push_url }}
      remote_timeout: 10s
      basic_auth:
        username: {{ prometheus_remote_write_username }}
        password: {{ prometheus_remote_write_password }}
  scrape_configs:
    - job_name: "prometheus"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["localhost:9090"]
          labels:
            instance: "kurtosis-sync-test"
    - job_name: "node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["172.17.0.1:9100"]
          labels:
            instance: "kurtosis-sync-test"
    - job_name: 'federate'
      scrape_interval: 60s
      honor_labels: true
      metrics_path: '/federate'

      params:
        'match[]':
          - '{__name__=~".+"}'   # Regex to match all metrics

      static_configs:
        - targets:
            - '172.17.0.1:32020'