---
- name: Create kurtosis-sync directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /opt/kurtosis-sync-test
    - /etc/kurtosis-sync

- name: Copy oneliner.sh to target directory
  copy:
    src: "{{ playbook_dir }}/../oneliner.sh"
    dest: /opt/kurtosis-sync-test/oneliner.sh
    mode: '0755'

- name: Create directory structure for client configs
  file:
    path: "/opt/kurtosis-sync-test/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - hoodi
    - sepolia
    - mainnet
    - results

- name: Copy network configuration files
  copy:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: "/opt/kurtosis-sync-test/{{ item }}"
  with_items:
    - hoodi/
    - sepolia/
    - mainnet/

- name: Create environment file for VictoriaMetrics credentials
  template:
    src: env.j2
    dest: /etc/kurtosis-sync/env
    mode: '0600'

- name: Copy systemd service file
  copy:
    src: "{{ playbook_dir }}/files/kurtosis-sync.service"
    dest: /etc/systemd/system/kurtosis-sync.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start kurtosis-sync service
  systemd:
    name: kurtosis-sync
    enabled: yes
    state: started