- hosts: all
  become: true
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: update ssh server
      ansible.builtin.apt:
        name: openssh-server
        state: latest

    - name: update ssh client
      ansible.builtin.apt:
        name: openssh-client
        state: latest
